
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
  id INT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  per DOUBLE NOT NULL
);
INSERT INTO STUDENT (id, name, per) VALUES (1001,'Raj',93.47);
INSERT INTO STUDENT (id, name, per) VALUES (1002,'Rahul',89.34);
INSERT INTO STUDENT (id, name, per) VALUES (1003,'Ajay',65.90);
INSERT INTO STUDENT (id, name, per) VALUES (1004,'Sonam',56.98);